

#ifndef PIC32CM_CM00_DMA_TRIGGER_SOURCE_H_
#define PIC32CM_CM00_DMA_TRIGGER_SOURCE_H_

#define   DMAC_CHCTRLB_TRIGSRC_DISABLE_Val          0
#define   DMAC_CHCTRLB_TRIGSRC_TSENS_Val            1
#define   DMAC_CHCTRLB_TRIGSRC_SERCOM0_RX_Val       2
#define   DMAC_CHCTRLB_TRIGSRC_SERCOM0_TX_Val       3
#define   DMAC_CHCTRLB_TRIGSRC_SERCOM1_RX_Val       4
#define   DMAC_CHCTRLB_TRIGSRC_SERCOM1_TX_Val       5
#define   DMAC_CHCTRLB_TRIGSRC_SERCOM2_RX_Val       6
#define   DMAC_CHCTRLB_TRIGSRC_SERCOM2_TX_Val       7
#define   DMAC_CHCTRLB_TRIGSRC_SERCOM3_RX_Val       8
#define   DMAC_CHCTRLB_TRIGSRC_SERCOM3_TX_Val       9
#define   DMAC_CHCTRLB_TRIGSRC_SERCOM4_RX_Val       10
#define   DMAC_CHCTRLB_TRIGSRC_SERCOM4_TX_Val       11
#define   DMAC_CHCTRLB_TRIGSRC_SERCOM5_RX_Val       12
#define   DMAC_CHCTRLB_TRIGSRC_SERCOM5_TX_Val       13
#define   DMAC_CHCTRLB_TRIGSRC_CAN0_DEBUG_Val       14
#define   DMAC_CHCTRLB_TRIGSRC_CAN1_DEBUG_Val       15
#define   DMAC_CHCTRLB_TRIGSRC_TCC0_OVF_Val         16
#define   DMAC_CHCTRLB_TRIGSRC_TCC0_MC0_Val         18
#define   DMAC_CHCTRLB_TRIGSRC_TCC0_MC1_Val         19
#define   DMAC_CHCTRLB_TRIGSRC_TCC0_MC2_Val         20
#define   DMAC_CHCTRLB_TRIGSRC_TCC0_MC3_Val         21
#define   DMAC_CHCTRLB_TRIGSRC_TCC1_OVF_Val         22
#define   DMAC_CHCTRLB_TRIGSRC_TCC1_MC0_Val         23
#define   DMAC_CHCTRLB_TRIGSRC_TCC1_MC1_Val         24
#define   DMAC_CHCTRLB_TRIGSRC_TCC2_OVF_Val         25
#define   DMAC_CHCTRLB_TRIGSRC_TCC2_MC0_Val         26
#define   DMAC_CHCTRLB_TRIGSRC_TCC2_MC1_Val         27
#define   DMAC_CHCTRLB_TRIGSRC_TC0_OVF_Val          28
#define   DMAC_CHCTRLB_TRIGSRC_TC0_MC0_Val          29
#define   DMAC_CHCTRLB_TRIGSRC_TC0_MC1_Val          30
#define   DMAC_CHCTRLB_TRIGSRC_TC1_OVF_Val          31
#define   DMAC_CHCTRLB_TRIGSRC_TC1_MC0_Val          32
#define   DMAC_CHCTRLB_TRIGSRC_TC1_MC1_Val          33
#define   DMAC_CHCTRLB_TRIGSRC_TC2_OVF_Val          34
#define   DMAC_CHCTRLB_TRIGSRC_TC2_MC0_Val          35
#define   DMAC_CHCTRLB_TRIGSRC_TC2_MC1_Val          36
#define   DMAC_CHCTRLB_TRIGSRC_TC3_OVF_Val          37
#define   DMAC_CHCTRLB_TRIGSRC_TC3_MC0_Val          38
#define   DMAC_CHCTRLB_TRIGSRC_TC3_MC1_Val          39
#define   DMAC_CHCTRLB_TRIGSRC_TC4_OVF_Val          40
#define   DMAC_CHCTRLB_TRIGSRC_TC4_MC0_Val          41
#define   DMAC_CHCTRLB_TRIGSRC_TC4_MC1_Val          42
#define   DMAC_CHCTRLB_TRIGSRC_ADC0_RESRDY_Val      43
#define   DMAC_CHCTRLB_TRIGSRC_ADC1_RESRDY_Val      44
#define   DMAC_CHCTRLB_TRIGSRC_SDADC_RESRDY_Val     45
#define   DMAC_CHCTRLB_TRIGSRC_DAC_EMPTY_Val        46
#define   DMAC_CHCTRLB_TRIGSRC_PTC_EOC_Val          47
#define   DMAC_CHCTRLB_TRIGSRC_PTC_WCOMP_Val        48
#define   DMAC_CHCTRLB_TRIGSRC_PTC_SEQ_Val          49

#endif /* PIC32CM_CM00_DMA_TRIGGER_SOURCE_H_ */